### ISSUE TITLE
Add dat file utility functions

### ISSUE THREAD

**Issue by amarcozzi** [silvxlabs/quicfire-tools#130]

**Comment by ntutland** [comment]
@amarcozzi There is a linked branch to this that gives a 404. Looking at dev-0.7.0 it doesn't seem to have been completed?

**Comment by ntutland** [comment]
I created a new branch where I am making changes (130-add-dat-file-utility-functions-2)

**Comment by amarcozzi** [comment]
@ntutland Sorry I think that we lost contact on this one. I see a read_dat_file function in dev-v0.7. Do you have anything else to add to the utils.py file from your branch? If so, can we add it directly to dev-v0.7?

Also, I'm cool with a 3D array plotter. I think that should go in a plotting.py, plots.py, visualization.py or something like though. Also, we should look into how to make optional dependencies for that. I don't think we should make something like pyvista a required dependecy for installing qf-tools.
