### ISSUE TITLE
Add multiple wind sensors

### ISSUE THREAD

**Issue by amarcozzi** [silvxlabs/quicfire-tools#86]
- Look at how the GUI does it for potential implementations

**Comment by amarcozzi** [comment]
Yes I completely agree! It's been a little bit since I looked at this, but I was thinking of having something like a sensor object managed by QU_metparams which can have a location and a list of times, speeds, and directions. Something along those lines.

**Comment by ntutland** [comment]
Thoughts on adding a from_csv method for windshifts? Might be good for working with actual sensor data, which is probably the main use case for windshifts

**Comment by ntutland** [comment]
This also brings up the interesting issue of not really having a wind speed and direction to use in create_simulation. Do we make the user put numbers in only to be replaced by their wind sensor data?
