### ISSUE TITLE
Rework zarr in v040

### ISSUE THREAD

**Issue by zacharycope0** [silvxlabs/quicfire-tools#88]
Create new branch to implement changes outlined in https://github.com/silvxlabs/quicfire-tools/issues/32

To do:
- [x] Add functionality so that zarr is only created if no zarr file exits
- [x] Build zarr with metadata for xarray compatibility
- [ ] Fix NAN in coordinate attributes 
- [ ] Have an option for rechunking zarr.

**Comment by amarcozzi** [comment]
Huh, that is weird. I wonder if it has something do with output from the range() function. Can you try generating coordinates with np.linspace or np.arange? Maybe something more numpy focused will fix the issue. Also, what do you think of having a cell_centered=True/False argument for the coordinates to be cell centered or lower left corner?

**Comment by zacharycope0** [comment]
@amarcozzi. I could try that. The thing is that the zarr_file object is reading out a 0. Also xarray is automatically changing the ints to floats. 

I was thinking about using cell center for the coordinates. Do you think it's worth having a flag? I wonder if that will just add confusion. I think cell centered is a reseaonable convention.

**Comment by amarcozzi** [comment]
In that case maybe we should just try cell centered and see if that fixes the problem. I think cell centered is a good convention, and there's not reason for a flag if it works and the other doesn't. What do you think of that?

**Comment by zacharycope0** [comment]
Sounds good. We will still have an issue with time = 0, but xarray would prefer that we use real data times anyway. Thats why I use the decode times=False argument.
https://github.com/silvxlabs/quicfire-tools/blob/900e36093f25a4fcbc7a698d530ab7071d0299ee/tests/test_output_module_zarr.py#L94-L96

**Comment by amarcozzi** [comment]
Closed with #164
