### ISSUE TITLE
Add .bin files to outputs.py

### ISSUE THREAD

**Issue by ntutland** [silvxlabs/quicfire-tools#93]
Move dict to json in data/outputs. Add the following:
- [x] emissions_distribution
- [x] qu_windu
- [x] qu_windv
- [x] qu_windw
- [x] qu_wplume
- [x] water_emissions

More?

**Comment by amarcozzi** [comment]
@ntutland What do you think of moving these dictionary definitions JSON files stored in data/outputs? That would get all of those dictionaries out of the outputs.py code and hopefully clean things up.

**Comment by ntutland** [comment]
Sounds good to me!
